"""ehp-db-2025-6-4-12-35-57

Revision ID: 0b877e87b256
Revises:
Create Date: 2025-06-04 12:35:58.420414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b877e87b256"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent",
        sa.Column("agen_cd_id", sa.Integer(), nullable=False),
        sa.Column("agen_tx_name", sa.String(length=250), nullable=False),
        sa.Column("agen_tx_prompt", sa.Text(), nullable=False),
        sa.Column("wiki_dt_created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("agen_cd_id"),
    )
    op.create_table(
        "country",
        sa.Column("coun_cd_id", sa.Integer(), nullable=False),
        sa.Column("coun_tx_name", sa.String(length=150), nullable=False),
        sa.Column("coun_cd_code", sa.String(length=5), nullable=False),
        sa.PrimaryKeyConstraint("coun_cd_id"),
    )
    op.create_table(
        "profile",
        sa.Column("prof_cd_id", sa.Integer(), nullable=False),
        sa.Column("prof_tx_name", sa.String(length=45), nullable=False),
        sa.Column("prof_cd_code", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("prof_cd_id"),
    )
    op.create_table(
        "tag",
        sa.Column("tag_cd_id", sa.Integer(), nullable=False),
        sa.Column("tag_tx_description", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("tag_cd_id"),
    )
    op.create_table(
        "wikiclip",
        sa.Column("wiki_cd_id", sa.Integer(), nullable=False),
        sa.Column("wiki_tx_title", sa.String(length=250), nullable=False),
        sa.Column("wiki_tx_content", sa.Text(), nullable=False),
        sa.Column("wiki_tx_url", sa.String(length=250), nullable=False),
        sa.Column("wiki_dt_created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("wiki_cd_id"),
    )
    op.create_table(
        "analysis",
        sa.Column("anls_cd_id", sa.Integer(), nullable=False),
        sa.Column("anls_tx_result", sa.Text(), nullable=False),
        sa.Column("wiki_dt_created_at", sa.DateTime(), nullable=False),
        sa.Column("agen_cd_id", sa.Integer(), nullable=False),
        sa.Column("wiki_cd_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agen_cd_id"],
            ["agent.agen_cd_id"],
        ),
        sa.ForeignKeyConstraint(
            ["wiki_cd_id"],
            ["wikiclip.wiki_cd_id"],
        ),
        sa.PrimaryKeyConstraint("anls_cd_id"),
    )
    op.create_table(
        "authentication",
        sa.Column("auth_cd_id", sa.Integer(), nullable=False),
        sa.Column("auth_tx_name", sa.String(length=150), nullable=False),
        sa.Column("auth_tx_email", sa.String(length=300), nullable=False),
        sa.Column("auth_tx_pwd", sa.String(length=150), nullable=False),
        sa.Column("auth_dt_created_at", sa.DateTime(), nullable=False),
        sa.Column("auth_st_active", sa.String(length=1), nullable=False),
        sa.Column("auth_st_confirmed", sa.String(length=1), nullable=False),
        sa.Column("auth_dt_confirmation", sa.DateTime(), nullable=True),
        sa.Column("auth_st_accept_terms", sa.String(length=1), nullable=False),
        sa.Column("auth_st_reset_password", sa.String(length=1), nullable=False),
        sa.Column("prof_cd_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prof_cd_id"],
            ["profile.prof_cd_id"],
        ),
        sa.PrimaryKeyConstraint("auth_cd_id"),
    )
    op.create_table(
        "wikiclip_tag",
        sa.Column("wiki_cd_id", sa.Integer(), nullable=False),
        sa.Column("tag_cd_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_cd_id"],
            ["tag.tag_cd_id"],
        ),
        sa.ForeignKeyConstraint(
            ["wiki_cd_id"],
            ["wikiclip.wiki_cd_id"],
        ),
        sa.PrimaryKeyConstraint("wiki_cd_id", "tag_cd_id"),
    )
    op.create_index("idx_tag_cd_id", "wikiclip_tag", ["tag_cd_id"], unique=False)
    op.create_index("idx_wiki_cd_id", "wikiclip_tag", ["wiki_cd_id"], unique=False)
    op.create_table(
        "authentication_log",
        sa.Column("aulo_cd_id", sa.Integer(), nullable=False),
        sa.Column("aulo_dt_logged_at", sa.DateTime(), nullable=False),
        sa.Column("aulo_nr_ip_address", sa.String(length=45), nullable=True),
        sa.Column("auth_cd_id", sa.Integer(), nullable=True),
        sa.Column("aulo_tx_event_type", sa.String(length=100), nullable=False),
        sa.Column("aulo_tx_reset_token", sa.String(length=150), nullable=True),
        sa.ForeignKeyConstraint(
            ["auth_cd_id"],
            ["authentication.auth_cd_id"],
        ),
        sa.PrimaryKeyConstraint("aulo_cd_id"),
    )
    op.create_table(
        "user",
        sa.Column("user_cd_id", sa.Integer(), nullable=False),
        sa.Column("user_tx_full_name", sa.String(length=250), nullable=False),
        sa.Column("user_dt_created_at", sa.DateTime(), nullable=False),
        sa.Column("auth_cd_id", sa.Integer(), nullable=True),
        sa.Column("coun_cd_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["auth_cd_id"],
            ["authentication.auth_cd_id"],
        ),
        sa.ForeignKeyConstraint(
            ["coun_cd_id"],
            ["country.coun_cd_id"],
        ),
        sa.PrimaryKeyConstraint("user_cd_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_table("authentication_log")
    op.drop_index("idx_wiki_cd_id", table_name="wikiclip_tag")
    op.drop_index("idx_tag_cd_id", table_name="wikiclip_tag")
    op.drop_table("wikiclip_tag")
    op.drop_table("authentication")
    op.drop_table("analysis")
    op.drop_table("wikiclip")
    op.drop_table("tag")
    op.drop_table("profile")
    op.drop_table("country")
    op.drop_table("agent")
    # ### end Alembic commands ###
