"""ehp-db-2025-6-16-17-56-50

Revision ID: 0d792b0451d6
Revises: b8c1d81987e7
Create Date: 2025-06-16 17:56:50.885591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d792b0451d6'
down_revision: Union[str, None] = 'b8c1d81987e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikiclip', sa.Column('wiki_js_related_links', sa.JSON(), nullable=True))
    op.alter_column('wikiclip', 'wiki_tx_title',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('wikiclip', 'wiki_tx_url',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=2000),
               existing_nullable=False)
    op.create_unique_constraint(None, 'wikiclip', ['wiki_tx_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wikiclip', type_='unique')
    op.alter_column('wikiclip', 'wiki_tx_url',
               existing_type=sa.String(length=2000),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.alter_column('wikiclip', 'wiki_tx_title',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.drop_column('wikiclip', 'wiki_js_related_links')
    # ### end Alembic commands ###
