"""ehp-db-2025-7-1-4-11-48

Revision ID: 182ea29eabf5
Revises: 9a5c5172b3a0
Create Date: 2025-07-01 04:11:49.558783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '182ea29eabf5'
down_revision: Union[str, None] = '9a5c5172b3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('user', sa.Column('user_tx_display_name', sa.String(length=150), nullable=True))
    op.add_column('user', sa.Column('user_dt_last_update', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('user', 'user_dt_created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['user_tx_display_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'user_dt_created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('user', 'user_dt_last_update')
    op.drop_column('user', 'user_tx_display_name')
    
    # ### end Alembic commands ### 