"""ehp-db-2025-7-11-6-36-8

Revision ID: 22d52737d331
Revises: 91b3077cacbe
Create Date: 2025-07-11 06:36:08.907668

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22d52737d331'
down_revision: Union[str, None] = '91b3077cacbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Default reading settings value
DEFAULT_READING_SETTINGS = {
    "font_size": "Medium",
    "fonts": {
        "headline": "System",
        "body": "System", 
        "caption": "System"
    },
    "font_weight": "Normal",
    "line_spacing": "Standard",
    "color_mode": "Default"
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column without default first
    op.add_column('user', 
        sa.Column('user_js_reading_settings', 
                  postgresql.JSONB(astext_type=sa.Text()), 
                  nullable=True)
    )
    
    # Set default value using ALTER TABLE
    default_settings_json = json.dumps(DEFAULT_READING_SETTINGS)
    op.execute(
        f"ALTER TABLE \"user\" ALTER COLUMN user_js_reading_settings SET DEFAULT '{default_settings_json}'::jsonb"
    )
    op.alter_column('user', 'user_js_readability_preferences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user', 'user_js_preferred_news_categories',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
    
    # Update existing users with default reading settings
    default_settings_json = json.dumps(DEFAULT_READING_SETTINGS)
    op.execute(
        f"UPDATE \"user\" SET user_js_reading_settings = '{default_settings_json}'::JSONB WHERE user_js_reading_settings IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_js_preferred_news_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user', 'user_js_readability_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('user', 'user_js_reading_settings')
    # ### end Alembic commands ###
