"""ehp-db-2025-6-18-17-24-45

Revision ID: 238480d29087
Revises: 0d792b0451d6
Create Date: 2025-06-18 17:24:46.438494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '238480d29087'
down_revision: Union[str, None] = '0d792b0451d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikiclip', sa.Column('user_cd_id', sa.Integer(), nullable=True))
    op.alter_column('wikiclip', 'wiki_dt_created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'wikiclip', 'user', ['user_cd_id'], ['user_cd_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wikiclip', type_='foreignkey')
    op.alter_column('wikiclip', 'wiki_dt_created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('wikiclip', 'user_cd_id')
    # ### end Alembic commands ###
