"""ehp-db-2025-7-22-23-15-14

Revision ID: 338eb8f993c8
Revises: 8b5edcada42b
Create Date: 2025-07-22 23:15:15.483220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '338eb8f993c8'
down_revision: Union[str, None] = '8b5edcada42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication', sa.Column('auth_tx_confirmation_token', sa.String(length=255), nullable=True))
    op.add_column('authentication', sa.Column('auth_dt_confirmation_token_expires', sa.DateTime(), nullable=True))
    op.alter_column('user', 'user_js_readability_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user', 'user_js_reading_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"fonts": {"body": "System", "caption": "System", "headline": "System"}, "font_size": "Medium", "color_mode": "Default", "font_weight": "Normal", "line_spacing": "Standard"}\'::jsonb'))
    op.alter_column('user', 'user_js_preferred_news_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_js_preferred_news_categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user', 'user_js_reading_settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"fonts": {"body": "System", "caption": "System", "headline": "System"}, "font_size": "Medium", "color_mode": "Default", "font_weight": "Normal", "line_spacing": "Standard"}\'::jsonb'))
    op.alter_column('user', 'user_js_readability_preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('authentication', 'auth_dt_confirmation_token_expires')
    op.drop_column('authentication', 'auth_tx_confirmation_token')
    # ### end Alembic commands ###
