"""ehp-db-2025-7-21-16-4-22

Revision ID: 5680bf2d3c61
Revises: 752c6f5eedd0
Create Date: 2025-07-21 16:04:23.630551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5680bf2d3c61'
down_revision: Union[str, None] = '752c6f5eedd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikiclip_detail',
    sa.Column('wiki_detail_cd_id', sa.Integer(), nullable=False),
    sa.Column('wiki_detail_tx_description', sa.Text(), nullable=True),
    sa.Column('wiki_detail_tx_type', sa.String(length=20), nullable=False),
    sa.Column('wiki_detail_dt_updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('wiki_cd_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wiki_cd_id'], ['wikiclip.wiki_cd_id'], ),
    sa.PrimaryKeyConstraint('wiki_detail_cd_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikiclip_detail')
    # ### end Alembic commands ###
