"""ehp-db-2025-7-22-22-59-24

Revision ID: 6a92660baab5
Revises: 8b5edcada42b
Create Date: 2025-07-22 22:59:25.589636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a92660baab5'
down_revision: Union[str, None] = '8b5edcada42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'user_js_readability_preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user', 'user_js_reading_settings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"fonts": {"body": "System", "caption": "System", "headline": "System"}, "font_size": "Medium", "color_mode": "Default", "font_weight": "Normal", "line_spacing": "Standard"}\'::jsonb'))
    op.alter_column('user', 'user_js_preferred_news_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('idx_user_created', 'wikiclip', ['user_cd_id', 'wiki_dt_created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_created', table_name='wikiclip')
    op.alter_column('user', 'user_js_preferred_news_categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('user', 'user_js_reading_settings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text('\'{"fonts": {"body": "System", "caption": "System", "headline": "System"}, "font_size": "Medium", "color_mode": "Default", "font_weight": "Normal", "line_spacing": "Standard"}\'::jsonb'))
    op.alter_column('user', 'user_js_readability_preferences',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
