"""ehp-db-2025-7-16-19-27-59

Revision ID: 752c6f5eedd0
Revises: bfc3bfea340a
Create Date: 2025-07-16 19:28:00.431784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '752c6f5eedd0'
down_revision: Union[str, None] = 'bfc3bfea340a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wikiclip', sa.Column('wiki_tx_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wikiclip', 'wiki_tx_summary')
    # ### end Alembic commands ###
