"""ehp-db-2025-7-29-8-27-51

Revision ID: 770ff4a9f26d
Revises: 0b9b325ad2cb
Create Date: 2025-07-29 08:27:51.849030

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "770ff4a9f26d"
down_revision: Union[str, None] = "0b9b325ad2cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "lens_type",
        sa.Column("lens_tp_cd_id", sa.Integer(), nullable=False),
        sa.Column("lens_tp_tx_name", sa.String(length=100), nullable=False),
        sa.Column("lens_tp_tx_description", sa.String(length=500), nullable=True),
        sa.Column(
            "lens_tp_dt_created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("lens_tp_cd_id"),
    )
    _ = op.create_table(
        "lens",
        sa.Column("lens_cd_id", sa.Integer(), nullable=False),
        sa.Column("lens_tx_title", sa.String(length=250), nullable=False),
        sa.Column("lens_tx_content", sa.Text(), nullable=False),
        sa.Column("lens_dt_created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("lens_tp_cd_id", sa.Integer(), nullable=False),
        sa.Column("lens_dt_disabled_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lens_tp_cd_id"],
            ["lens_type.lens_tp_cd_id"],
        ),
        sa.PrimaryKeyConstraint("lens_cd_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lens")
    op.drop_table("lens_type")
    # ### end Alembic commands ###
