"""ehp-db-2025-7-9-18-16-6

Revision ID: 7a58aaa176c3
Revises: 7f3ab8e31047
Create Date: 2025-07-09 18:16:07.467818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a58aaa176c3'
down_revision: Union[str, None] = '7f3ab8e31047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_tx_avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_tx_avatar')
    # ### end Alembic commands ###
