"""ehp-db-2025-6-6-16-48-27

Revision ID: 7e4174519044
Revises: 05165e3052a4
Create Date: 2025-06-06 16:48:27.913357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e4174519044'
down_revision: Union[str, None] = '05165e3052a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authentication', sa.Column('auth_tx_reset_token', sa.String(length=255), nullable=True))
    op.add_column('authentication', sa.Column('auth_dt_reset_token_expires', sa.DateTime(), nullable=True))
    op.alter_column('authentication', 'auth_tx_pwd',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authentication', 'auth_tx_pwd',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('authentication', 'auth_dt_reset_token_expires')
    op.drop_column('authentication', 'auth_tx_reset_token')
    # ### end Alembic commands ###
