"""ehp-db-2025-7-8-12-2-27

Revision ID: 97403192758c
Revises: 9a5c5172b3a0
Create Date: 2025-07-08 12:02:27.984444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97403192758c'
down_revision: Union[str, None] = '9a5c5172b3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_js_readability_preferences', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('user_bl_email_notifications', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_bl_email_notifications')
    op.drop_column('user', 'user_js_readability_preferences')
    # ### end Alembic commands ###
