"""ehp-db-2025-6-20-13-52-19

Revision ID: 9a5c5172b3a0
Revises: 238480d29087
Create Date: 2025-06-20 13:52:19.702748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5c5172b3a0'
down_revision: Union[str, None] = '238480d29087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wikiclip_wiki_tx_url_key', 'wikiclip', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wikiclip_wiki_tx_url_key', 'wikiclip', ['wiki_tx_url'])
    # ### end Alembic commands ###
