"""ehp-db-2025-6-9

Revision ID: ab0ecdfc1b9a
Revises: 0b877e87b256
Create Date: 2025-06-10 18:10:01.311733

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab0ecdfc1b9a"
down_revision: Union[str, None] = "0b877e87b256"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "authentication", sa.Column("auth_nr_retry_count", sa.Integer(), nullable=False)
    )
    op.add_column(
        "authentication",
        sa.Column("auth_dt_last_login_attempt", sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("authentication", "auth_dt_last_login_attempt")
    op.drop_column("authentication", "auth_nr_retry_count")
    # ### end Alembic commands ###
